version: '3'
services:
  backend:
    build:
      context: ./backend  # Path to your backend folder
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env  # Relative path to the .env file
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8080
    networks:
      - chatbot-network

  frontend:
    build:
      context: ./frontend/chatbot
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge
